### ISSUE TITLE
Error in ML scraping

### ISSUE THREAD

**Issue by dario-ramos** [dario-ramos/housing_scraper#12]
2020-11-24 23:51:10,706 - root - ERROR - Error processing provider mercadolibre.
<class 'AttributeError'>
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    new_properties = process_properties(provider_name, provider_data)
  File "/home/user/Documents/Freelance/housing_scraper/providers/processor.py", line 36, in process_properties
    for prop in provider.next_prop():
  File "/home/user/Documents/Freelance/housing_scraper/providers/base_provider.py", line 21, in next_prop
    yield from self.props_in_source(source)
  File "/home/user/Documents/Freelance/housing_scraper/providers/mercadolibre.py", line 34, in props_in_source
    title = title_section.find('span').get_text().strip() + \
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by dario-ramos** [comment]
Fixed
