### ISSUE TITLE
Fix web driver bug in Bonifacio

### ISSUE THREAD

**Issue by dario-ramos** [dario-ramos/housing_scraper#24]

**Comment by dario-ramos** [comment]
Stack trace from Heroku:

```
Error in provider bonifacio. Detailed error information: Traceback (most recent call last):
  File "main.py", line 28, in <module>
    new_properties = process_properties(
  File "/app/providers/processor.py", line 24, in process_properties
    for prop in provider.next_prop():
  File "/app/providers/base_provider.py", line 21, in next_prop
    yield from self.props_in_source(source)
  File "/app/providers/bonifacio.py", line 27, in props_in_source
    properties, page_content = self.scrape_properties(
  File "/app/providers/bonifacio.py", line 48, in scrape_properties
    _ = WebDriverWait(driver, timeout).until(
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=87.0.4280.88)
```

**Comment by dario-ramos** [comment]
The Remax provider has a very similar issue, might have the same solution
